// Disposable DB and injected fake transport: never places real calls.
import assert from "node:assert/strict";
import {mkdtempSync,writeFileSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {spawnSync} from "node:child_process";
import twilio from "twilio";
async function main() {
 const file=join(mkdtempSync(join(tmpdir(),"mc-voice-")),"test.sqlite");writeFileSync(file,"");
 process.env.DATABASE_URL=`file:${file}`;
 process.env.ANNOUNCEMENT_VOICE_ENABLED="true";process.env.ANNOUNCEMENT_VOICE_BASE_URL="https://voice.example.test";
 process.env.TWILIO_ACCOUNT_SID="AC"+"a".repeat(32);process.env.TWILIO_AUTH_TOKEN="isolated-test";process.env.TWILIO_VOICE_FROM="+14155551234";
 const m=spawnSync(process.execPath,["node_modules/prisma/build/index.js","migrate","deploy"],{env:process.env,encoding:"utf8"});assert.equal(m.status,0,m.stderr);
 const {prisma}=await import("../src/lib/prisma");
 const {queueAnnouncementCalls,dispatchAnnouncementCalls,processVoiceCallback}=await import("../src/lib/announcementVoice");
 const {POST}=await import("../src/app/api/voice/announcements/[key]/route");
 try {
  for(const [id,role,phone,active] of [["admin","ADMIN",null,true],["a","EMPLOYEE","9876543210",true],["b","EMPLOYEE","9876543211",true],["invalid","EMPLOYEE",null,true],["inactive","EMPLOYEE","9876543212",false]] as const) await prisma.user.create({data:{id,name:id,employeeCode:id,passwordHash:"unused",role,phone,active,approved:true}});
  const a=await prisma.announcement.create({data:{title:"Test announcement",body:"Please arrive on time.",authorId:"admin"}});
  await prisma.$transaction(tx=>queueAnnouncementCalls(tx,a.id));
  assert.equal(await prisma.announcementCall.count(),3);assert.equal(await prisma.announcementCall.count({where:{status:"INVALID_NUMBER"}}),1);
  let calls=0;
  const send=async()=>({sid:"CA"+(++calls).toString(16).padStart(32,"0")});
  const now=new Date(Date.now()+1000);
  await dispatchAnnouncementCalls(now,send);await dispatchAnnouncementCalls(now,send);assert.equal(calls,2);
  let first=await prisma.announcementCall.findUniqueOrThrow({where:{announcementId_userId:{announcementId:a.id,userId:"a"}}});
  const params={AccountSid:process.env.TWILIO_ACCOUNT_SID,To:first.phone!,CallSid:first.callSid!,Digits:"1"};
  const url=`https://voice.example.test/api/voice/announcements/${first.attemptKey}?event=ack`;
  const request=(signature:string)=>new Request(url,{method:"POST",headers:{"x-twilio-signature":signature,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams(params)});
  assert.equal((await POST(request("bad"),{params:Promise.resolve({key:first.attemptKey!})})).status,403);
  const signature=twilio.getExpectedTwilioSignature(process.env.TWILIO_AUTH_TOKEN,url,params);
  assert.equal((await POST(request(signature),{params:Promise.resolve({key:first.attemptKey!})})).status,200);
  await POST(request(signature),{params:Promise.resolve({key:first.attemptKey!})});
  await processVoiceCallback(first.attemptKey!,"status",{...params,CallStatus:"completed"},now);
  assert.equal(await prisma.announcementAck.count(),1);
  first=await prisma.announcementCall.findUniqueOrThrow({where:{id:first.id}});assert.equal(first.status,"ACKNOWLEDGED");
  const second=await prisma.announcementCall.findUniqueOrThrow({where:{announcementId_userId:{announcementId:a.id,userId:"b"}}});
  const status={To:second.phone!,CallSid:second.callSid!,CallStatus:"no-answer"};
  await processVoiceCallback(second.attemptKey!,"status",status,now);
  await processVoiceCallback(second.attemptKey!,"status",status,new Date(+now+1000));
  await dispatchAnnouncementCalls(new Date(+now+299999),send);assert.equal(calls,2);
  await dispatchAnnouncementCalls(new Date(+now+300000),send);assert.equal(calls,3);
  assert.equal(await processVoiceCallback(second.attemptKey!,"ack",{...status,Digits:"1"}),false);
  const retry=await prisma.announcementCall.findUniqueOrThrow({where:{id:second.id}});
  await processVoiceCallback(retry.attemptKey!,"status",{...status,CallSid:retry.callSid!},new Date(+now+300001));
  await dispatchAnnouncementCalls(new Date(+now+900000),send);assert.equal(calls,3);
  assert.equal((await prisma.announcementCall.findUniqueOrThrow({where:{id:second.id}})).status,"UNANSWERED");
  process.env.ANNOUNCEMENT_VOICE_ENABLED="false";
  const disabled=await prisma.announcement.create({data:{title:"No setup",body:"Test",authorId:"admin"}});
  await prisma.$transaction(tx=>queueAnnouncementCalls(tx,disabled.id));
  assert.equal(await prisma.announcementCall.count({where:{announcementId:disabled.id,status:"NOT_CONFIGURED"}}),2);
  process.env.ANNOUNCEMENT_VOICE_ENABLED="true";await dispatchAnnouncementCalls(new Date(+now+900000),send);assert.equal(calls,3);
  const skipped=await prisma.announcement.create({data:{title:"Eligibility",body:"Test",authorId:"admin"}});
  await prisma.$transaction(tx=>queueAnnouncementCalls(tx,skipped.id));
  await prisma.announcementAck.create({data:{announcementId:skipped.id,userId:"a"}});
  await prisma.user.update({where:{id:"b"},data:{active:false}});
  await dispatchAnnouncementCalls(new Date(Date.now()+1000),send);assert.equal(calls,3);
  assert.equal(await prisma.announcementCall.count({where:{announcementId:skipped.id,status:"ACKNOWLEDGED_ON_WEB"}}),1);
  assert.equal(await prisma.announcementCall.count({where:{announcementId:skipped.id,status:"SKIPPED"}}),1);
  const uncertain=await prisma.announcement.create({data:{title:"Uncertain send",body:"Test",authorId:"admin"}});
  await prisma.$transaction(tx=>queueAnnouncementCalls(tx,uncertain.id));
  await dispatchAnnouncementCalls(new Date(Date.now()+1000),async()=>{throw new Error("timeout");});
  assert.equal(await prisma.announcementCall.count({where:{announcementId:uncertain.id,status:"UNKNOWN"}}),1);
  await dispatchAnnouncementCalls(new Date(Date.now()+2000000),send);assert.equal(calls,3);
  await prisma.announcement.delete({where:{id:a.id}});assert.equal(await prisma.announcementCall.count({where:{announcementId:a.id}}),0);
  console.log("PASS: durable queue, eligible recipients, invalid phones, no duplicate dialing, signed acknowledgement, replay safety, retry timing/cap, stale callbacks, disabled setup and deletion cascade. No live calls.");
 } finally {await prisma.$disconnect();}
}
void main();
