// Run only against a separately migrated test DB and a local app pointing to it.
import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
const base=process.env.TEAM_TEST_BASE_URL, databaseUrl=process.env.TEAM_TEST_DATABASE_URL;
if(!base||!['localhost','127.0.0.1'].includes(new URL(base).hostname)||!databaseUrl?.endsWith('/team-workspace-test.sqlite')) throw new Error('Use a localhost TEAM_TEST_BASE_URL and an isolated TEAM_TEST_DATABASE_URL ending /team-workspace-test.sqlite.');
const db=new PrismaClient({datasources:{db:{url:databaseUrl}}});
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const day=n=>{const d=new Date(today+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const req=async(cookie,path,method='GET',body)=>{const r=await fetch(base+path,{method,headers:{cookie,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'manual'});let data;try{data=await r.json();}catch{data={};}return {status:r.status,data};};
const ok=async(...args)=>{const r=await req(...args);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};
try{
 const passwordHash=await bcrypt.hash('Isolated-team-test-123',4);
 for(const [id,name,role,approved] of [['team-admin','Test Admin','ADMIN',true],['team-a','Asha Devi','EMPLOYEE',true],['team-b','Rohan Singh','EMPLOYEE',true],['team-pending','Pending Member','EMPLOYEE',false]]) await db.user.upsert({where:{id},create:{id,name,employeeCode:id.toUpperCase(),passwordHash,role,approved,active:true,mustChangePassword:false,createdAt:new Date('2026-01-01T00:00:00Z')},update:{employeeCode:id.toUpperCase(),active:true,approved,passwordHash,mustChangePassword:false,muteChat:false}});
 const login=async code=>{const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({employeeCode:code,password:'Isolated-team-test-123'})});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];};
 const admin=await login('team-admin'),a=await login('team-a'),b=await login('team-b'),pending=await login('team-pending');
 assert.equal((await req('', '/api/team/chat')).status,403);
 assert.equal((await req(pending,'/api/team/chat')).status,403);
 await ok(a,'/api/team/profile','PATCH',{birthdayMonth:9,birthdayDay:20,shareBirthday:false});
 assert.ok(!(await ok(b,'/api/team/birthdays')).birthdays.some(p=>p.id==='team-a'));
 assert.ok((await ok(admin,'/api/team/birthdays')).birthdays.some(p=>p.id==='team-a'));
 assert.equal((await req(a,'/api/team/profile','PATCH',{birthdayMonth:2,birthdayDay:30})).status,400);
 await ok(a,'/api/team/profile','PATCH',{shareBirthday:true});assert.ok((await ok(b,'/api/team/birthdays')).birthdays.some(p=>p.id==='team-a'));
 const ann=(await ok(admin,'/api/announcements','POST',{title:'Team update for testing',body:'Please acknowledge this isolated test announcement.'})).announcement;
 let notices=await ok(a,'/api/team/notifications');const note=notices.items.find(n=>n.entityKey===ann.id);assert.ok(note&&!note.readAt);
 await ok(a,'/api/team/notifications','PATCH',{id:note.id});
 assert.equal((await ok(a,`/api/announcements/${ann.id}/detail`)).announcement.acknowledgements.length,0);
 await ok(a,`/api/announcements/${ann.id}/ack`,'POST',{});await ok(a,`/api/announcements/${ann.id}/ack`,'POST',{});
 const report=await ok(admin,`/api/announcements/${ann.id}/ack`);assert.equal(report.people.find(p=>p.id==='team-a').acknowledgements.length,1);assert.equal(report.people.find(p=>p.id==='team-b').acknowledgements.length,0);
 assert.equal((await req(a,`/api/announcements/${ann.id}/ack`)).status,403);
 await ok(b,'/api/team/profile','PATCH',{muteChat:true});
 const m=(await ok(a,'/api/team/chat','POST',{body:'Hello team!'})).message;
 assert.equal(await db.notification.count({where:{userId:'team-b',kind:'CHAT',entityKey:m.id}}),0);
 const reply=(await ok(b,'/api/team/chat','POST',{body:'Thanks!',replyToId:m.id})).message;
 await ok(b,`/api/team/chat/${m.id}`,'POST',{emoji:'👍'});let chat=await ok(a,'/api/team/chat');assert.ok(chat.messages.find(x=>x.id===m.id).reactions.some(r=>r.userId==='team-b'));
 await ok(b,`/api/team/chat/${m.id}`,'POST',{emoji:'👍'});assert.equal((await ok(a,'/api/team/chat')).messages.find(x=>x.id===m.id).reactions.length,0);
 await ok(a,'/api/team/chat','PATCH',{lastSeenId:reply.id});assert.equal(await db.notification.count({where:{userId:'team-a',kind:'CHAT',entityKey:reply.id,readAt:null}}),0);
 assert.equal((await req(b,`/api/team/chat/${m.id}`,'DELETE')).status,403);
 await ok(admin,`/api/team/chat/${m.id}`,'DELETE');chat=await ok(a,'/api/team/chat');assert.equal(chat.messages.find(x=>x.id===m.id).body,'Message removed');assert.equal(chat.messages.find(x=>x.id===reply.id).replyTo.body,'Message removed');
 assert.equal((await req(a,'/api/team/schedule','POST',{})).status,403);
 const shift=(await ok(admin,'/api/team/schedule','POST',{userId:'team-a',workDate:day(3),startsAt:day(3)+'T09:00:00+05:30',endsAt:day(3)+'T18:00:00+05:30',note:'Morning shift'})).shift;
 assert.equal((await ok(b,`/api/team/schedule?from=${day(3)}&to=${day(3)}`)).shifts.length,0);
 const leave=(await ok(a,'/api/team/requests','POST',{kind:'LEAVE',fromDate:day(3),toDate:day(3),reason:'Family event'})).request;
 assert.equal((await req(b,`/api/team/requests/${leave.id}`,'PATCH',{status:'CANCELLED'})).status,403);
 assert.equal((await req(admin,`/api/team/requests/${leave.id}`,'PATCH',{status:'APPROVED'})).status,409);
 await ok(admin,`/api/team/schedule/${shift.id}`,'DELETE');await ok(admin,`/api/team/requests/${leave.id}`,'PATCH',{status:'APPROVED',reviewNote:'Enjoy your day.'});
 assert.ok((await ok(a,`/api/team/schedule?from=${day(3)}&to=${day(3)}`)).leave.some(l=>l.id===leave.id));
 assert.equal((await req(admin,'/api/team/schedule','POST',{userId:'team-a',workDate:day(3),startsAt:day(3)+'T09:00:00+05:30',endsAt:day(3)+'T18:00:00+05:30'})).status,409);
 const correction=(await ok(a,'/api/team/requests','POST',{kind:'CORRECTION',fromDate:day(-2),reason:'Forgot clock-out during test',proposedIn:day(-2)+'T09:00:00+05:30',proposedOut:day(-2)+'T18:00:00+05:30'})).request;
 await ok(admin,`/api/team/requests/${correction.id}`,'PATCH',{status:'APPROVED'});
 const record=await db.attendanceRecord.findUnique({where:{userId_workDate:{userId:'team-a',workDate:day(-2)}}});assert.equal(record.approvalStatus,'PENDING');assert.equal(await db.attendanceAudit.count({where:{recordId:record.id,action:'CORRECTED'}}),1);
 const stale=(await ok(a,'/api/team/requests','POST',{kind:'CORRECTION',fromDate:day(-2),reason:'Another correction',proposedIn:day(-2)+'T09:00:00+05:30',proposedOut:day(-2)+'T19:00:00+05:30'})).request;
 await db.attendanceRecord.update({where:{id:record.id},data:{approvalStatus:'APPROVED'}});
 assert.equal((await req(admin,`/api/team/requests/${stale.id}`,'PATCH',{status:'APPROVED'})).status,409);
 assert.ok((await ok(b,'/api/team/requests')).requests.every(r=>r.userId==='team-b'));
 const summary=await ok(a,'/api/team/home');assert.ok(summary.summary);assert.ok(!JSON.stringify(summary).includes('salaryRs'));assert.ok(!JSON.stringify(summary).includes('hourlyRateRs'));
 await db.user.update({where:{id:'team-b'},data:{active:false}});for(const path of ['/api/team/chat','/api/team/notifications','/api/team/schedule'])assert.equal((await req(b,path)).status,403);
 await db.user.update({where:{id:'team-b'},data:{active:true}});
 console.log('PASS: birthday privacy, pending/deactivated access, announcement fan-out, read vs acknowledgement, idempotent acknowledgements, chat replies/reactions/moderation/muting/read state, own-data scopes, shift/leave conflicts, correction audit + stale guard, salary privacy.');
}finally{await db.$disconnect();}
